- main.py
Removed a positional argument `reason` in `warn_clear()` , as well as a repeated command definition, which would fail slash command execution.
> Remove positional argument in `warns_clear` command

- main.py
Initially, on command execution, the bot would reply with fallback string, even when the request was successfully completed. This patch fixes the incorrect string returned on successful command execution.
> Fix warn success string

- main.py
All occurrences of `cash` and `crypto` have been replaced with `wallet` and `bank` respectively. This was done so that it can similarly match the current framework which is used in isobot.
Crypto may be added back into the framework later, as a different system.
> Replace all mentions of `cash` and `crypto`

- main.py
Yet another enhancement to the v2 currency framework. This allows users to deposit cash to their bank account. The bank account does not have any limit (for now).
This command has some rules aswell:
- Amount cannot be less than 1.
- Float values are not supported (well even I'm not sure).
- Amount cannot be more than what the user has in their wallet.
- The positional `amount` argument may be left blank. This will result in depositing max amount of coins in bank account.
> Add `deposit` command

- main.py
At this point I might aswell finish the core currency framework before the end of the month! Yep! another currency framework v2 update.
This adds `daily`, `weekly` and `monthly` commands, with their respective cooldowns.
- Daily = 24 hours
- Weekly = 7 days
- Monthly = 31 days
> Add `daily`, `weekly` and `monthly` commands

- main.py
Again, another update to the v2 currency framework. This allows users to withdraw cash from their bank account. There is currently no wallet cap.
This command has some rules aswell:
- Amount cannot be less than 1.
- Float values are not supported (well even I'm not sure).
- Amount cannot be more than what the user has in their bank account.
- The positional amount argument may be left blank. This will result in withdrawing max amount of coins in wallet.
> Add `withdraw` command

- main.py
Yes. Another addition to the currency framework. This adds `work` command, which lets players earn 10000-20000 coins per 30-minute shifts. It is expected to be the main source of income for users.
> Add `work` command

- README.md
Removes all mentions of 'stock' and replace it with 'Isobot lazer'.
> Updated to match rename

- main.py
There was an issue with `deposit` and `withdraw` commands where when attempting to deposit or withdraw, it would throw an exception. This should fix the bug.
> Patch `deposit` and `withdraw` commands

- main.py
Welcome to another update for the currency framework!! This adds `gift` command, which lets anyone gift an amount of coins to someone else. There are some restrictions to this command, however. They are as follows:
- Amount must not be less than 0 coins.
- Amount must not be greater than what the user has in their wallet.
> Add `gift` command

- main.py
- Convert all mentions of 'wallet' to string
There was an issue where, when the `scout` or `beg` commands were requested by a user, it would throw an exception. This should fix the issues.
> Patch all commands calling 'wallet'

- utils/logger.py
This will force any info logs, warn logs, or error logs to initially be spooled to the working console.
This sets the log file paths as second priority, allowing those to soft-fail.
> Log stuff to console

- .replit
- main.py
- utils/ping.py
This change allows the hosting to be monitored and calaulated, and also allows replit to work correctly 24/7 non-stop with this client. This adds the handling code, as well as the libraries required to operate it.
Libraries:
- utils.ping
Requires:
- Replit (hosting platform)
- Uptimerobot (monitoring platform)
> Add hosting monitoring support

- main.py
This change might render previous hosting environments useless, because the paths used in replit is `/home/runner/isobot-lazer` and it has no support for `.` path extenders (to my knowledge). 
However, this can be changed at any time, if we need to migrate hosting platforms again.
> Make paths replit-compatible

- main.py
If a user tried to sell an item, it would say that the item was not available and it's supposed to `return`.
But instead, it would remove the item from the user's inventory, and also not give selling price to their inventory.
This patch will fix the item lookup error message being returned, as well as the issue where it would not give the user the item's selling price.
> Fix "item not found" error while selling items

- config/shop.json
- main.py
This adds implementation for binoculars in the `` command. It gives an advantage for the user who has it in their inventory by using the formula given below to boost the outcome of the scout command.
Formula: 
```py
x *= 1.425
```
The binocular's never wears off unless and until the user sells all of their binoculars and removes them from their inventory.
> Add implementation for binoculars in `/scout`

- main.py
This change doesn't affect the command for ACTUAL moderators.
https://tenor.com/view/thor-strike-admin-ban-admin-ban-gif-22545175
> Make kick and ban response on `MissingPermissions` funnier

- main.py
**To prevent spam requests and raiding.** This is mainly done to prevent the bot from getting rate-limited (which would lead to more downtime, screw Discord API rate limits). Also, it helps prevent raid behavior and prevents nuking and other stuff.
- Kick: 3 seconds
- Ban: 3 seconds
- Warn: 2 seconds
> Make moderation command cooldowns

- main.py
`/whoami` can be used to see your information, or another user's information.
Self-view:
Other user:
More user information will come to this command soon!
> Add `/whoami` command

- main.py
This will make the bot reply with a random "name" and "response" whenever the `/beg` command is run. This is not for any functional purpose, instead only to make the bot feel more open-worlded and less dull and more fun!
> Add random names and replies to `/beg` command

- main.py
`/stroketranslate` can be used (FOR FUN) to convert a combination of random letters into words and sentences. Go crazy.
I also had to make universal paths because I was tired of typing in the entire path whenever I wanted to link to another file. Now, the working directory can automatically be called from using `wdir` variable. Nice!
> Add `/stroketranslate` command

- main.py
`/prediction` can be used (FOR FUN) to predict a yes or no answer to a question. Please note that the bot simply replies with "yes" or "no" and you shouldn't ALWAYS take it seriously! Have fun!
> Add `/prediction` command

- main.py
A system where people can donate to their favourite users: Let it be friends, family, YouTubers, or other devs. This command can be used as a way to donate money to support them, however you want.
* The receiver's ID
* An active discord account (new accounts who haven't messaged yet will not accept donations)
* Enough cash to donate
> Add `/donate` command

- main.py
A dev command that can be used by the DEVS to modify any user's balance. This means they can easily add or remove your coins lol
> Add dev command `/modify_balance`

- api/auth.py
- api/runtimeconfig.json
- main.py
This will make the client ask the user if they want to use a custom token (their own token) in console, if the token is not inputed in the `runtimeconfig.json` file. This update doesn't actually change anything with the commands, it just improves the performance and maintenance of the bot.
<h6>NOTE: runtimeconfig.json can be found in `api/runtimeconfig.json`.</h6>
> Add custom token support and saving

- main.py
As per the GNU GPL 3.0 License states: If there is terminal interaction with the program, then it should display License info upon use. That's why we added this feature to our client: so that we can reassure the user that we are committed to being open-source.
> Add GPL3.0 license notice upon client startup

- main.py
This lets any user gift a `giftable` item from their inventory to any other user.
> Create a gifting system

- scripts/redirect.js
[CodeFactor](https://www.codefactor.io/repository/github/pybotdevs/isobot-lazer) found an issue: This number literal will lose precision at runtime.
It's currently on:
[scripts\redirect.js:16](https://www.codefactor.io/repository/github/pybotdevs/isobot-lazer/source/main/scripts/redirect.js#L16)
> Convert `client_id` number literal to string literal

- main.py
Doing this will help make command development easier, as well as simplifying the code and also allowing for better framework development.
> Move currency balance management commands to separate class

- main.py
This should help with improving code quality, that's pretty much it.
> Explicitly define all bare exception as `Exception`

- .gitignore
When working on a branch to commit to the repository, developers might have to enter their own bot token to debug their work. The exact `runtimeconfig.json` filename was not in .gitignore, which means that if they forget to remove the token, it could get into the pull request and it could get stolen. This is an important dev fix so please pull this change.
> Fix a typo in gitignore

- config/words.json
This resolves a bug where the `/stroketranslate` command would throw an exception if the user inputted a space in the command's argument. This adds whitespaces to `words.json` so that it will ignore any spaces in the command argument.
> Add whitespace support to `/stroketranslate`

- main.py
The license disclaimer output contained indent blocks in it which were also printed upon startup. This removes the indent blocks and makes it look neater.
> Fix license disclaimer output

- main.py
Added to match 1 hour wait for rewards, and to prevent *"m4513r h4xx0r5"* from exploiting the command.
> Add 1 hour cooldown for autogrind command

- main.py
The error handler is still not working as it lacks support for discord_slash. I will update it again once I find a solution to this.
> Patch bot's error handler

- main.py
This command returns an embed link with this repository's link as well as our GitHub organization link.
> Add GitHub repository link command as `/repo`

- slash_commands.md
This documentation is being added because some users who might be developing for isobot might have some confusion with `discord_slash` command options. This markdown documentation contains `create_option()` usage and examples, usage of `create_option()` in an example slash command, and the different option types for the `option_type` argument.
> Add Discord Slash command documentation

- main.py
This also fixes a bug where if a plugin is disabled, it will not return the command but instead it will ignore the checks like nothing ever happened.
> Debloat command plugin configuration checks

- framework/isobot/embedengine.py
- main.py
***Uses the EmbedEngine library from NKA Framework***
EmbedBuilder lets you make custom embeds with maximum configuration for your server. That's all I really have to say for this.
> Add `/embedbuilder` command

- main.py
This is done to make Dank Memer users more familiar with the deposit and withdraw syntax as they start using isobot. However, if an invalid keyword (any value that isn't a number and isn't "max" or "all") is used as amount, it might break the bot. I will release a fix for this or I will fix it in the same issue.
> Set "max" and "all" as keywords for max amount in `/deposit` and `/withdraw` commands

- main.py
This minigames makes you guess whether the actual number is higher or lower than the hint number, that the bot gives you. You can choose any one of these options by typing and sending them in the chat:
* high: if you think the number is higher than the hint
* low: if you think the number is lower than the hint
* jackpot: if you think the number is the same as the hint (it's very rare!)
***NOTE:*** If you choose jackpot and it is correct, you will win **5 million coins**!
> Create new `/highlow` minigame

- framework/isobot/colors.py
- framework/isobot/currency.py
I forgot that these are called classes, not functions
> Remove redundant parentheses from classes in framework

- framework/isobot/currency.py
Adds `self` keyword where needed
> Add missing keywords to `framework.isobot.currency`

- main.py
It would return this exception in stdout for absolutely no reason (if someone were to message in a server where no one is AFK)
```py
Ignoring exception in on_message
Traceback (most recent call last):
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
await coro(*args, **kwargs)
File "main.py", line 104, in on_message
for x in user_presence[str(ctx.guild.id)].keys(): uList.append(x)
KeyError: '873417861589262367'
```
It's kinda annoying seeing this exception flooding the verbose log when there isn't even anything wrong with the code or the bot.
> Fix AFK system returning an error if the message guild isn't already indexed in the `user_presence` database

- main.py
`@@everyone` looks cursed, and there's no use in displaying the `@everyone` role anyway (because it's obvious), so I just removed it.
> Remove `@@everyone` role from being displayed on `/whoami` user profile

- poetry.lock
The Pycord package wasn't being used by any internal modules or the bot client itself, so to avoid extra unnecessary space being taken up on storage and to reduce the size of the poetry lock file, I decided it was best to simply remove the Pycord dependency package from the poetry lock file.
> Sync poetry lock file to remove Pycord from packages

- config/commands.json
- main.py
This command will let any user view basic isobot profile stats about themselves, or any other specified user. 
As of now, there isn't a proper userdat system or data after-processing, which means that the command cannot show more detailed info (eg: level progress, work history, rob history, gain/loss graphs etc.).
But the command **can** show all of these stats as of now:
* user level
* user xp
* wallet balance
* bank balance
* networth
*Remember, more changes will be added to this command soon.*
> Add `/profile` command to let users view isobot profile stats

- config/commands.json
- main.py
This conflict was caused due to the `/open` command, which is also used as another command in the `save()` command. Due to this bug, whenever the database was supposed to save cached data, it would fail and return `BaseCommandObject` exception instead.
This caused many problems, including rendering the entire earning and spending logic in the economy system, useless.
This patch should fix it, and allow the database to save data correctly.
> Fix duplicate naming error causing save fails when `save()` is called

- config/commands.json
- main.py
*Suggested by GlitchedAI_3248 on Discord*
This system lets users view total computed net-worth of themselves, or any other user on the `/balance` command, `/networth` command, `/whoami` command, and more.
This was originally supposed to sum up the user's balance in their wallet and bank accounts, as well as parse every item's sell price in the user's inventory and return the value. However, I ran into some issues while making that work, so that is temporarily (or even permanently) disabled. I will add it back if i can fix the system.
> Make user networth display on `/balance` and `/networth` commands

- main.py
- utils/ping.py
Done to match rename and release of isobot's new codebase to stable client.
* All links containing `isobot-lazer` in it has been changed to `isobot`
* All names containing `isobot-lazer` in it has been changed to `isobot`
> Replace all mentions of `isobot-lazer` with `isobot`

- cogs/e
- config/commands.json
- main.py
Cog support is being removed as discord.py doesn't support slash commands in cogs. I might add it back if I can get Py-cord to work correctly with the client.
> Remove support for cogs

- main.py
- themes/halloween.theme.json
This theme system allows anyone to contribute new themes for isobot (of course, through GitHub pull requests) which can be used to decorate the bot for special events (isobot's anniversary, lazer day) or general holidays/events (Halloween, Christmas). Any theme will go into the `themes/` folder in the bot client's root directory, and it will be loaded directly on startup.
> Add isobot theme system and add `Halloween Theme 2022` to theme list

- main.py
The `/deposit` and `/withdraw` command responses now show more information in the form of an embed. Now you can see your old wallet/bank balance, as well as the new wallet/bank balance, making isobot even easier to use.
> Add more info in the `/deposit` and `/withdraw` command responses

- main.py
Reduces the amount of unnecessary bot text in a server channel. Also, reactions can most probably be used with plain message contexts (like the new help embed message).
> Send help command list embeds to user DMs instead of in server channel

- main.py
This patch changes the retrieval of user context data from cache to a direct API request while sending a DM response, as using cache is more likely to fail rather than force-fetching new data. 
Also the `hide` parameter has been changed to `ephemeral` parameter for hidden messages in the `respond()` and `send()` commands. (in Pycord)
> Fix issue where help command does not send embed in user DMs and returns no response error

- main.py
This should reduce the amount of "spam" being sent in the server's #general channel from isobot (and also make it harder to collect presents, so that I can make the event even more competitive).
> Add more delay between present drops in New Years special in-game event

- main.py
Doing this prevents unnecessary warnings from showing up on certain Python source analysis tools.
> Remove unused library imports in main bot script

- main.py
Timestamp checking has been moved to be processed after asyncio delay.
> Prevent bot from hanging due to infinite loop caused when checking timestamps

- main.py
I have no idea how I screwed this up
> Fix cog load, unload and reload commands not showing command output

- cogs/economy.py
- cogs/minigames.py
- cogs/moderation.py
> Implement new cooldown system for slash commands with cooldowns

- cogs/maths.py
- config/commands.json
> Move all maths area commands to `SlashCommandGroup` in maths cog

- cogs/events.py
- main.py
I'm not adding this cog to the initialization code because there aren't any ongoing events right now. I can add it whenever necessary, though.
> Move special event commands to a separate cog file

- api/auth.py
- api/runtimeconfig.json
- main.py
You can switch from local to replit or vice-versa in the runtime configuration by modifying the value in the `replit` key in the runtimeconfig.json file. 
`true` enables replit mode (storing bot token in replit environment variable) and `false` uses the token provided in the runtimeconfig.json file. The environment variable name for the bot token is `TOKEN`.
If replit runtime mode is enabled, then the `token` value in runtimeconfig.json can be left empty. But if it is disabled, a token will be needed in the configuration file.
Automatic detection may come sometime in the future.
> Add runtime mode option for switching between local and replit modes

- cogs/levelling.py
- cogs/utils.py
- main.py
Another subtle, yet important cog update. 
This also adds functions to the levelling library for retrieval of user levels and xp.
> Move some utility commands from main file to cog

- cogs/economy.py
- cogs/utils.py
- main.py
This also adds a new function addition to the economy library: `get_user_count()` to get the total number of cached users.
> Move some more utility commands from main file to cog

- cogs/isocoin.py
- main.py
> Move all IsoCoin commands from main file to a cog

- cogs/fun.py
- main.py
Hopefully one of the last command transfers to cogs.
> Move `/prediction` from main file to fun cog

- main.py
This will help give more insights into why a cog failed to load, rather than just checking the developer console.
> Add exception type display in embed on failing of any cog command

- cogs/moderation.py
- main.py
Should help reduce client memory usage by a little bit.
> Add functions in moderation library for making guild id and user id keys in warnings db

- cogs/economy.py
From this update onwards, all purchases made at the store will include a 3% tax. Any tax that amounts to a decimal number will be rounded for convenience sake. For your reference, the tax percentage and taxable amount will be displayed on the purchase invoice. 
All incoming taxes will soon go to the upcoming isobot treasury.
> Add shop tax calculation and invoice display in `/buy` command

- main.py
The help command will now show command autocomplete in the `command` parameter, while checking for information about a particular command.
> Help command option lists

- cogs/fun.py
- config/commands.json
The kill command lets you kill people *for fun*. Using this command on others is only for entertainment purposes, and not for gaining advantage.
> Add `/kill` command

- cogs/moderation.py
- main.py
Includes only `/kick` and `/ban` commands.
(thank you again, akiko)
> Move existing moderation commands to new cog

- cogs/levelling.py
I had to remove the user avatar display for the embed footer, which was the reason why the embed wasn't showing.
> Fix embed not returning in `/rank` command

- cogs/levelling.py
When I get too comfortable with my code:
> Fix bugs in `/leaderboard` command

- main.py
This should have been done so long ago.
> Remove Halloween 2022 theme from client initialization

- cogs/economy.py
- cogs/levelling.py
- config/commands.json
- main.py
This command lets you see the global ranking of all the users based on their net worth. This command is copied from the levelling leaderboard command, but some adjustments have been made to it to work with user net worth.
Originally, I would have set the leaderboard to display 10 users' rankings, but I instead set it to 5, as fetching more users' data from the api could hang the bot and the command would have expired by then.
> Add leaderboard command for viewing ranking for user net worth

- cogs/utils.py
- config/commands.json
This command lets users generate any image they want through isobot, with the help of DALL-E 2 and the OpenAI API.
No request or image data is stored on our servers and this command is made in compliance with OpenAI's code of conduct and terms & conditions.
Example of `/generate_image` (prompt: "an armchair in the shape of an avocado"):
> Add `/generate_image` command to let users generate images using DALL-E modal

- cogs/economy.py
- cogs/minigames.py
- main.py
Yet another code quality update :+1:
> Fix string opening and closing formatting and remove redundant fstrings

- main.py
Should prevent excess memory usage by a *little bit*
> Disable IsoBank auth module from loading on startup

- cogs/economy.py
- cogs/minigames.py
- cogs/utils.py
- framework/isobot/currency.py
- main.py
Instead of using raw code and multiple statements to interact with the currency database, these functions have been simplified into single methods which makes transactions fast and easy.
It also provides additional functionality like currency tracking and logging to prevent scamming and makes new features like user bank account statements possible.
Also, CurrencyAPI makes it possible for other applications and systems outside isobot to interface with the currency system, making things like 3rd-party transactions and sales possible using isobot's currency. (coming soon)
CurrencyAPI is currently in functionality and more features will be rolled out soon for all users to use.
> Migrate old currency system to CurrencyAPI

- cogs/fun.py
- config/commands.json
This command lets users owoify text (uwu girl moment)
> Add `/owoify` fun command

- config/commands.json
- main.py
This command was previously being used when the databases were managed all at `main.py`, instead of in separate bot cogs.
Now, since all the databases are automatically managed by these bot cogs, there is no more use for the `/sync` command, which means its time to call it off from isobot.
> Remove `/sync` DevTools command

- main.py
Just a few code-quality updates :)
> Improve source code quality

- cogs/utils.py
- config/commands.json
This lets users use a custom output resolution for their AI-generated image while executing the `/generate_image` command.
**Resolution argument format:** `{width}x{height}`
For example, if I want an image generated with 512p resolution, then i will use `512x512` in the resolution argument.
> Add custom image output resolution for `/generate_image` command

- cogs/utils.py
- main.py
***MERGE THIS PULL REQUEST ONLY AFTER #296 IS MERGED!***
This change should make development easier, better debugging and testing for commands, and general debugging purposes.
(Referenced from issue #295)
> Add command error details output for uncaught errors

- cogs/economy.py
- cogs/fun.py
- cogs/isocard.py
- cogs/moderation.py
- cogs/osu.py
This was done to support the addition of `Exception` handling in the bot's exception handler.
> Remove all `Exception` type exceptions

- cogs/utils.py
- framework/isobot/colors.py
- framework/isobot/currency.py
- framework/isobot/embedengine.py
- main.py
This makes the source code less bloated.
> Simplify and shorten module import structures

- cogs/automod.py
- cogs/economy.py
- cogs/isobank.py
- cogs/levelling.py
- cogs/minigames.py
- main.py
Looks like Linux subsystems don't need them 😄
> Remove all references of `wdir`

- main.py
This should provide more insight into why a cog failed to load, disable, or reload.
> Improve exception tracing in cog commands

- cogs/economy.py
- cogs/levelling.py
- cogs/utils.py
- framework/isobot/db/levelling.py
- main.py
This update switches from using direct database modification to library based modification. This makes database modification faster for the bot, easier to work for developers, and more efficient for you.
> Switch from using raw levelling db modification to library-based modification

- cogs/utils.py
The new username system features usernames without the discriminator system. (eg: notsniped#4573 -> notsniped)
Since some users still either have not updated their username, and bot users have not received the update yet, the Discord API will return new usernames's discriminators as `#0`.
To prevent this from reflecting on commands which depend on the full username, this change adds a feature to remove usernames with discrim `#0`.
> Remove discrim from username display if user is using new username format

- cogs/utils.py
> Improve code quality

- framework/isobot/db/levelling.py
When the levelling db library attempts to add or remove levels from a user (through framework), it ends up failing and returning a `KeyError` exception.
This was because in the levelling db library, the `add_levels()` and `remove_levels()` methods were attempting to modify the `levels` value (non-existant) instead of the `level` value (actual key name).
This patch aims at resolving this issue and providing a bug-free user experience.
> Fix a bug which returns `KeyError` when modifying user level

- cogs/economy.py
- framework/isobot/db/items.py
- framework/isobot/shop.py
- main.py
This means that, yes, the items database system is getting upgraded with framework module support!
I also moved ShopData to a separate framework module (for convenience sake).
> Add base implementation for items db framework module

- cogs/economy.py
- framework/isobot/db/items.py
All commands utilizing the items database from now on, will work on the `framework.isobot.db.items` module.
> Migrate items db instances completely to framework module

- framework/isobot/currency.py
- framework/isobot/db/automod.py
- framework/isobot/db/items.py
- framework/isobot/db/levelling.py
- framework/isobot/db/userdata.py
- framework/isobot/db/weather.py
Previously, when a request was fired to save the isobot databases, the client would add indents to every single line in the database. This does look nice for the eyes, but this also causes major computational overhead (especially when working with the items database), and is one of the main reasons causing the Replit server to crash.
This update removes indenting while saving databases. Now, the databases may not look as nice, but at least it should be able to spare the server a bit.
> Remove overhead caused by indenting databases

- cogs/utils.py
Apparently PyCord updated their library to depreciate the `discord.User.avatar_url` reference and switch to `discord.User.avatar`.
I didn't know until I found new bugs in the commands, and I finally read the PyCord documentation again.
> Fix `/status` command failure caused by `avatar_url`

- cogs/maths.py
This update allows users using the `/area circle` command to set different pi values, including 22/7, 3.14, and 3.
> Allow varying values for pi

- cogs/maths.py
This makes the implementation of new and different types of math commands easier, and also makes finding these commands easier in isobot.
> Rename `area` slash command group to `math`

- cogs/afk.py
- cogs/utils.py
- framework/isobot/db/presence.py
- main.py
More framework modules! (the last one, thank god)
> Move all AFK and presence database functions to a new framework module

- cogs/utils.py
Useful, I guess? (only for me lol)
> Add commands to manage isobot's command registry

- api/auth.py
- api/runtimeconfig.json
- cogs/osu.py
- cogs/reddit.py
- cogs/utils.py
- cogs/weather.py
Looks like bro is finally cooking
> Add new runtime configuration options and support for external tokens in `api.auth` library

- cogs/fun.py
Use this command if you want to sound cool like a m4st3r h4xx0r 😎 
(especially for those skids out there)
> Add `/hackertext` command to turn any text into m4st3r h4xx0r text

- cogs/maths.py
More maths commands lets goooo
> Add commands for calculating volume of 3D objects

- cogs/economy.py
> Add `/hack` command to hack people's wallets for coins

- cogs/economy.py
> Improve bot responses for some economy commands, and add detailed disclaimer on item purchase invoices

- cogs/economy.py
I had to make this for the new chess collection of items :)
> Add support for `collectables` items type in `/inventory`

- cogs/economy.py
Apparently, the Discord API can only make a slash command with a maximum of 25 choices.
After the addition of multiple new items, the `item ids` count has exceeded 25 items, which runs into Discord's slash command limitation and prevents commands from being synced to the bot.
Hence, item id selectors have been removed from all economy slash commands as a counteractive measure. For reference, all item ids can be viewed and searched from through the new `/all_item_ids` command.
> Remove item id choices for economy slash commands

- main.py
This new standalone setup method allows for cleaner source code management, as well as ease of future improvements and flexibility.
> Replace old setup code with a standalone `initial_setup()` method

- main.py
Thank you devs and everyone for supporting the isobot project :)
> Add `/credits` command to show gratitude towards our developers

- utils/logger.py
Some of these improvements include:
- More configurability for `info()`, `warning()` and `error()`
- New class `StartupLog()` which allows bot client startup logs to be displayed and saved to a log file
- More backend improvements to optimize the logging module
> Add new significant improvements to isobot's logging system

- framework/isobot/db/automod.py
- framework/isobot/db/items.py
- framework/isobot/db/levelling.py
- framework/isobot/db/presence.py
- framework/isobot/db/userdata.py
- framework/isobot/db/weather.py
This change allows us to optimize the bot client and framework, and also allows to cut down on bloat.
> Migrate all colors in framework modules to `framework.isobot.colors` module for stdout colors

- framework/isobot/currency.py
- framework/isobot/db/items.py
- framework/isobot/db/levelling.py
- framework/isobot/db/userdata.py
- framework/isobot/db/weather.py
- main.py
This was made in compliance with the Discord bot ToS (road to bot verification lets gooooo)
> Add `/delete_my_data` command to allow any user to delete all of their isobot data permanently

- main.py
This allows the bot's pinging server to be deployed, even when Replit mode is disabled through runtime options configuration. This is useful for local bot deployments, if the server's local ip is used to track client uptime, etc.
Go to `api/runtimeconfig.json`, and set `ping_server_override=true`
> Allow pinging server deployment to be overridden through runtime options

- framework/isobot/currency.py
> Add `load()` and `save()` methods to simplify json data transactions in currency framework module

- main.py
This feature will allow the bot to show how active a specific guild is. This also has support for new DM flagging.
For privacy reasons, any message or media content is not logged to the bot client. Only the username, server name and channel name are logged.
This is currently a basic implementation of the feature, actual commands will come later in the future for everyone to enjoy!
> Add isobot server activity logger

- cogs/maths.py
- config/commands.json
The last stretch of 3d object calculation commands for isobot.
> Add surface area calculation commands for 3d objects

- api/auth.py
- api/runtimeconfig.json
This helps in debugging the bot client on programs like VS Code by allowing tokens to be easily imported, and minimizes the risk of accidentally leaking bot tokens on Git.
> Add support for alternate token paths for debugging

- .gitignore
- logs/error-log.txt
- logs/info-log.txt
- main.py
Now, the log files and its directory will not be pre-added to the client directory. It will now be completely auto-generated by the bot client upon startup, if they are missing.
This allow allows the usage of `.gitignore` to prevent generated logs in log files from being accidentally uploaded to Github.
> Add auto-generation of log files to client upon startup

- cogs/automod.py
Basically update the attribute name for guild icon in order to fetch it and display it in the embed correctly, because Pycord changed the `icon_url` attribute which led to an `AttributeError` and that led to an embed creation exception, which led to the whole command failing. Anyway, thankfully, its all fixed now. 😌 
This is what happens when you update Pycord.
> Fix issue in `/automod` where server icon fails to display

- main.py
Hopefully this should prevent confusion for new people
> Add tip for new level 1 users to disable level-up messages

- cogs/economy.py
- framework/isobot/currency.py
Finally figured out how to fix it after working on levels leaderboard command 🙂
> Fix fetching of user context data from API and re-enable `/leaderboard_nw`

- cogs/utils.py
Oh btw I also updated the Top.gg and DBL listings. They should be more accurate now 👍
> Add `/vote` to let users vote for isobot on Top.gg and DBL

- cogs/utils.py
Now the fact is that I genuinely needed this command for my usage...
> Add `/avatar` command to let users see other user avatars

- main.py
Two years.
I'm not even going to lie, this bug was there in the bot since the very beginning of the codebase rework.
It was absolutely haunting. It used to make me think every night: "How would I be able to fix this?"
No amount of ChatGPT debugging or documentation resolution was able to provide me with a solution for it. Eventually, I landed on the conclusion that I wouldn't be able to fix it, and I just left it, allowing the AFK system and the automod features to rot in the dark.
But finally, after some time of thinking with a fresh and rejuvenated mind, after 2 whole years, I was finally able to find a fix for it... and the fix was only 3 lines long.
Turns out it was that in PyCord's latest update they turned `discord.Bot()` into a `discord.Client()` replica by adding its arguments, so …
> FINALLY enable the `message_content` intent flag for the bot client

- cogs/economy.py
- cogs/fun.py
- config/commands.json
- framework/isobot/algorithms.py
Idea referenced from issue #250 :)
> Completely revamp `/kill` to allow users to gain cash and rewards from it

- cogs/automod.py
- config/commands.json
- framework/isobot/db/automod.py
- main.py
Why are these automod features so goddamn large
> Add link blocker automod feature to automatically delete set blacklisted links, allow whitelisted links, or block links all together

- main.py
@dtxc wanted this 👍 
(you're welcome)
> Improve general isobot code readability

- main.py
I realised this bug from when I was writing RateBot (surprisingly related ikr)
> Use `json.dump()` instead of directly writing new data when generating new databases

- cogs/utils.py
Ok but how did I not even add this command to the bot yet
> Add `/ping` to measure server-API latency

- cogs/automod.py
This will prevent exceeding the specified Discord API slash command character limits while processing new commands, and also allows the `automod` cog to load completely.
> Shorten some slash command names and descriptions

- cogs/levelling.py
This will provide a little bit more info on how much more XP is required for the user to level up, from their current level.
> Add user level XP targets in `/rank` command 

- main.py
I thought that this was a valid event. Apparently its not.
Okay how is this not even a valid event yet?? It would be so useful if it actually was tbh
> Remove unused test client event `after_invoke`

- main.py
Just removing another redundant variable
> Remove timestamp construction while firing error handler

- main.py
As a result of this addition, the `/help` command was forced to be separated into `/help list` and `/help info` to correctly accommodate its different purposes.
- Use `/help list` to show all available/usable commands in the bot, and to search for specific commands
- Use `/help info` to display detailed descriptions and information on a specific command
> Add search query support to help command

- cogs/isocard.py
- framework/isobot/db/isocard.py
Apparently its never really over...
> Move all IsoCard database functions from cog to a separate framework module

- cogs/moderation.py
- framework/isobot/db/warnings.py
- main.py
This is a pretty neat and useful moderation feature which lets server and community owners, admin, moderators, and other staff warn their server members for doing activity that breaks their rules, warning for fun (we wont judge), or for other reasons too.
- `/warn`: The basic warning system feature. This command can only be used by people with the `Manage Messages` permission in the server. This command warns a user for a specific reason by sending them a DM, as well as logging it to the server warnings log.
- `/clear_all_warnings`: This command basically lets staff with the `Manage Messages` permission in the server to clear all warnings from a specific user. This will wipe their name clean from the server warnings log, but it won't delete any of their warning DMs. (maybe use this if …
> Add a server warning system to let server staff warn their members for certain activity

- config/commands.json
- main.py
This also greatly improves the design and appearance of the help command embed, from an ugly long list of commands into a neatly-organized categorized panel.
> Automatically sort commands into different categories in `/help` list

- cogs/utils.py
- config/commands.json
- main.py
This command provides detailed information about a specific server, consisting of information like
- Server Creation Date
- Member Count
- Server Owner
- Number of Different Channel Types
- Roles
- Threads
- Invite links
- Server Verification Level
- Custom Expressions (emojis, stickers)
> Add `/serverinfo` command to provide detailed information about a specific server

- cogs/fun.py
`x` is the minimum limit, and `y` is the maximum limit for the random number.
> Add `/randomnumber` command to let users choose a random number between `x` and `y`

- cogs/fun.py
Just to clarify, this command is for **fun purposes only**. I am **not** homo.
Please use and take this command in a light-hearted and fun manner. Do not use this command to bully, harass, or be homo towards other users.
> Add `/howgay` command to rate the gayness of a user

- cogs/serverconfig.py
- framework/isobot/db/serverconfig.py
- main.py
> Add `/serverconfig autorole` to allow server managers to automatically assign roles to newly-joined members

- cogs/serverconfig.py
- framework/isobot/db/serverconfig.py
- main.py
Done through the `/serverconfig levelup_override_channel` command. This basically overrides the DM level-up messages and sends the message to a specified server channel instead.
This can be enabled or disabled at any time by members with the `Manage Guild` permission.
> Add ability to send level-up messages to a server channel, instead of user DMs

- cogs/serverconfig.py
- config/commands.json
- framework/isobot/db/serverconfig.py
- main.py
I guess this is already self-explanatory enough...
- `/serverconfig enable_verification`: Enable verification for all new members in the server. (admin perms required)
- `/serverconfig disable_verification`: Disable verification for all new members in the server. (admin perms required)
- `/start_verification`: Start the verification process for a new member in the server (if member verification is enabled) (server-only)
- `/verify`: Verify membership for a specific server using a one-time verification code (dm-only)
> Add server user verification system to let server owners require all new members to verify before using the server

- cogs/afk.py
- cogs/automod.py
- cogs/moderation.py
- cogs/serverconfig.py
- cogs/utils.py
This will help prevent unexpected errors due to lack of guild data by running commands in isobot DMs, for commands that require information about guilds (servers).
> Set a few bot slash commands as server-only

- cogs/serverconfig.py
- main.py
This allows isobot to be configured in a server to automatically send welcome and goodbye messages to a specified channel whenever someone joins or leaves the server. (configurable only by people with the `Manage Server` permission)
> Add welcome and goodbye autoresponder messages to serverconfig

- cogs/serverconfig.py
- framework/isobot/db/serverconfig.py
- main.py
This allows server managers and owners to configure isobot (using serverconfig commands) to respond in a channel to certain messages from other users, with a custom response! 
You can set multiple autoresponders server-wide or limited to a specific channel, set whether the trigger is case-sensitive, as well as being choosing the trigger condition, either when a specific line of text is found in any message, or if the text matches the message content.
More features may be added soon to autoresponders (like response modes), so stay alert!
(autoresponders are configurable only by server members with the `Manage Messages` permission)
> Add custom server message autoresponder system to serverconfig

- cogs/economy.py
- cogs/fun.py
- main.py
**NOTE:** This has been done only wherever needed.
This helps make the client more efficient by using tuples in some places instead of lists, as lists may contain more built-in methods than required for some things. Maybe even use up less memory...
> Optimize client efficiency by replacing some lists with tuples

- cogs/maths.py
If the discriminator of the equation is below 0, it means that the roots of the quadratic equation are imaginary. Otherwise this command will return both roots of a given quadratic equation (its coefficients `a`, `b`, and `c`).
> Add command to solve for roots in a quadratic equation

- index.html
The isobot logo should now appear on your browser's page tab, if it's supported. (im sorry if you're on light mode)
> Add isobot light favicon to the website

- index.html
This is being done now since I recently added server verification as a new isobot feature. (this will be fully released in the next isobot release)
> Remove `(soon)` from the `Server Verification` item

- cogs/isocard.py
- framework/isobot/isocard.py
- framework/isobot/isocardtxn.py
- main.py
The final release of the IsoCard System includes the following new features:
1. **Transaction IDs** for all existing payments on the IsoCard network. They can be identified using their _first three letters_, and the _last six numbers_.
2. A **transaction history log**, to log all existing IsoCard transactions related to a specific user
3. Optimize a bunch of existing things, and fix __a lot__ of bugs
**This is the final development phase of IsoCard, and the system will be in full deployment. Any additional (or) new bugs will be addressed in the coming Isobot patches.**
> Release Isocard System Final Phase (Phase 4)

- cogs/economy.py
This economy system update consists of the following changes:
1. A new **slash command group** for all **shop-related commands**, and also split **shop list** and **item view** into **two separate commands**
2. Improved **reliability and efficiency** for all shop commands
3. Improved __command descriptions__ for some commands
4. Completely add **all items information** in `/shop list`
> Completely rework the economy `/shop` commands

- .gitignore
- api/auth.py
- main.py
This is to make updates easier by preventing data loss. (iykyk)
> Move `runtimeconfig.json` configuration file from main bot client directory to isobot data directory

- main.py
- network_check.py
This update makes the client check for network connectivity before running the client completely, and keeps retrying until a network connection is established (useful for server environments).
This also checks for any network-related issues while logging in the bot client to Discord, and logs any network errors in the process. This system also gives the client 5 attempts to try to log in, after which the client automatically terminates.
> Add network check and autorestart for failed bot client login

- cogs/devtools.py
- cogs/economy.py
- cogs/levelling.py
- main.py
This update has also moved all of the DevTools commands to a new slash command group, to make finding the commands easier.
(only developers will understand 🤫)
> Move all of the DevTools commands to a new cog

- api/auth.py
- cogs/devtools.py
The `superusers` option is a list which can contain an infinite number of Discord user IDs.
Every single user ID present in this runtimeconfig option will have unrestricted access to all internal devtools commands.
> Add superusers runtime option to default runtimeconfig in `initial_setup`

- cogs/afk.py
- cogs/automod.py
- cogs/devtools.py
- cogs/fun.py
- cogs/isobank.py
- cogs/isocard.py
- cogs/isocoin.py
- cogs/levelling.py
- cogs/maths.py
- cogs/minigames.py
- cogs/weather.py
Improves some things like punctuation and grammar in some commands descriptions, and also worked on adding missing docstrings for some commands that needed them.
> Improve some command descriptions in cogs

- main.py
This was created so that people who love isobot in different servers can easily and quickly add the bot to their own servers too!
This also contains some other links for our official website, and for the Discord Bot support server.
> Add a server invite command for isobot
