- main.py
This basically combines some imports into single lines.
> Debloat a few imports

- main.py
An update to the currency-framework. This command lets players earn coins quickly by begging.
> Add beg command 

- main.py
A better version of `beg` command. You can gain 550 to 2000 coins every 30 seconds by scouting your area for cash.
> Add `scout` command

- main.py
This command is another addition to currency-framework v2. This lets people steal from other people. Ofc, this implements the more precise chance calculation system, as well as some rules:
- You must have 5k in your wallet.
- The other person must have 5k in their wallet.
- There is a 50/50 success rate. You could either flush out someone's income, or you could yourself get stolen from!
> Add `rob` command

- config/shop.json
- main.py
This is an addition to the newly-added `inventory` command. 
For now, only tools can be bought. However, new items will further be added.
> Add `shop` command

- config/shop.json
- main.py
fixed a bunch of (grammar and much more) mistakes
fixed monthly cmd wrong msg output ("weekly")
debloated with f string
smoothened descriptions of slashies
> Fix grammatical errors

- main.py
This is to finish any incomplete aspects or work with the `inventory` command, which was previously incomplete. It also completes the `buy` command by adding plugin-check code.
> Complete `inventory` command and add Plugin-Check code for `buy` command

- main.py
why tf is raise and except becoming functions notsniped
> Fix exception-handling builtins

- main.py
> Fix slash command description grammar

- utils/logger.py
> fixed error log path

- main.py
> Fix single and plural "coin" and changed weird vocabulary

- config/shop.json
- main.py
The hunt command makes use of the rifle tool, by allowing you to hunt for animals (or things xd) to sell and earn cash!
> Add `hunt` command

- main.py
> Changed shop desc because it was inaccurate

- config/shop.json
May add more later, out of ideas
> Add binoculars in shop config file

- config/shop.json
- main.py
This adds the `/fish` command to isobot lazer. It lets users (who own at least one fishing pole ) to fish items from the ocean. Available loot is as follows:
- shrimp
- fish
- rare fish
- exotic fish
-  jellyfish
- shark
Item sell pricing will be updated soon.
> Add `fish` command

- main.py
This is a basic implementation for the `sell` command in the isobot rewrite. This is basic and made for core functionality, and will be improved/worked on over time.
> Add basic implementation for `sell()`

- main.py
> Merge this, just do it.

- main.py
> Fix bug which allowed to sell more than a user had

- main.py
- utils/logger.py
This lets the program check if the logs path exists. And if it doesn't, it will create one for you.
> Make dir creation system for logs

- main.py
> Make db creation system for item `shark`

- config/shop.json
- main.py
`/dig` command will let users dig the ground, to earn coins or get usable/sellable items! There will be a **50-75%** success rate for this command, and a user must own 1 or more shovels to execute the command. Each 
- Coins (1000 coins to 5000 coins, must be a **common value only**)
- Another shovel xd
- ant
- stickbug
- rock
- gold
- ancient coinbomb (i seriously have to revive that sh*t)
- rare lootbox
- nothing
- you died and got nothing, nice
Tasks are provided in #55
> Add `/dig` command to currency API

- main.py
Cooldown values for `/rob` and `/bankrob`:
- `/rob`: 1 minute to plan another robbery
- `/bankrob`: 5 minutes to plan another "heist"
> Add cooldowns for `/rob` and `/bankrob` commands

- main.py
`/echo` can be used to make clean announcements, updates, or to simple play and mess around with the bot. It posts the message content you want into the same channel you are currently in.
> Add `/echo` command

- utils/logger.py
CoLoUrSSSSSSSssssSs ~~just to look nice lmao~~
> Add colours to `utils.logger.colours` for stdout

- main.py
Jokes aside, I am making `/meme`, `/osumeme`, `/linuxmeme`, `/nothecker` (for keeping the legacy alive for now), `/ihadastroke` and `/engrish` for this update. Happy reddit(ing)!
> Add reddit media commands

- main.py
Finally, instead of using the old item db creation system, which used to fail a LOT and didnt work properly, we have the new version. The new version if very efficient, and also is able to repair corrupted data within the blink of an eye. This will definitely make development for new items easier for the devs.
```py
for z in shopitem:
if z in str(ctx.author.id):
pass
else:
items[str(ctx.author.id)][str(z)] = 0
save()
```
Enjoy!
> Make a better db item creation system

- main.py
Also known as "stats for nerds". Jk, but you gotta admit, you can't not agree that it looks cool.
> Add client info command

- index.html
If you were wondering what the website without bootstrap or resources would look like? Well here you go.
> Fix resources and bootstrap paths

- main.py
> Group imports into single line

- .vscode/extensions.json
Can be used for new developers to get started with isobot-lazer development.
> Add `ms-python.python` and `ms-toolsai.jupyter` to recommended extensions

- main.py
> Fix message context issue in `on_message` event and add AFK remove timed autodelete

- main.py
> Sort library imports

- main.py
This makes first-time use of the new framework.
> Use `Colors()` class from framework

- main.py
When an AFK user is mentioned, or someone mentions you when you're AFK, the bot will send a message in the same channel alerting the user that the person they are trying to reach is currently unavailable.
> Trigger AFK Alert on AFK user mention

- main.py
Done just to make the bot look fresh :)
> Update the bot status

- main.py
It completely forgot to refer to the item db :skull:
> Fix item database parser

- main.py
Yes, I seriously messed that up
> Fix messed up method definitions for `/edit_rank` and `/edit_xp`

- main.py
Always remember to fstring, kids!
> fstring `/rank` display embed's title

- framework/isobank/authorize.py
- framework/isobank/manager.py
- main.py
A small addition to the IsoBank API.
> Add basic implementation of IsoBank accounts

- main.py
Using `keys()` method be like:
> Fix autogrind command not giving completion rewards due to a list type error

- main.py
> Send embed on `/repo` command invokation

- framework/isobank/authorize.py
- main.py
**:tada: IsoBank account regestrations are now finally open!!! :tada:**
Yes! You can finally register your own account with IsoBank and get a permanent and safe coin archiving service. This archiving service lets you deposit, and withdraw coins at any time you want, and you can also link multiple Discord accounts with your IsoBank account and transfer coins between them that way. This also means that you can have shared accounts with multiple people having authorized access to your currency!
Don't worry, your coins are in safe hands with us. We will make weekly backups of our IsoBank databases, so incase something goes horribly wrong with isobot's database or isobot itself, you can be rest-assured that your hard-earned money is kept safe with us.
At the moment, we are <u>only accepting …
> Release IsoBank registration to all users

- .dev/MINIGAMES_IDEAS.md
I will need to make at least a few of these minigames to actually move Isobot lazer with the main Isobot client.
yes
> Add Isobot minigame ideas for development

- main.py
A simple minigame where the user has to guess the correct number that the bot is thinking of (from 1 to 10). This can be played by using `/guessthenumber` command in isobot.
*It's not that easy btw*
> Add new "Guess the Number" minigame to the economy system

- README.md
> Add more prominent invite link to readme

- main.py
The client will automatically create a currency log for you, if it is missing, or on first launch.
> Add log file auto-creation for currency log if path does not exist

- .editorconfig
- .vscode/extensions.json
This configuration has been added to allow maintaining of consistency between authors and commits and files.
> Add EditorConfig file to project configuration

- pyproject.toml
Mainly an update for replit environments which still use poetry packager system.
> Use pyproject.toml configuration file to configure poetry build system

- main.py
Done for proper Discord embed color usage.
> Use hex conversion to convert theme colors into color codes

- main.py
Introducing some new people to the isobot beg command, now featuring **the developers**, **Technoblade** and some other people as well!
> Add new `/beg` command name responses

- main.py
This command features glitched, nasty, failing software bugs!
> Add `/softwaregore` reddit media command

- config/commands.json
- main.py
This command can find the square root of any positive number. Returns "imaginary number" response if a negative number is provided as argument.
> Add `/squareroot` maths command

- config/commands.json
- maths.py
A = √(s x (s - a) x (s - b) x (s - c))
> Add `/area_triangle` maths command

- main.py
Cogs are only getting better and better.
> Use loops while loading cogs instead of using bare sequences

- reddit.py
This is what happens when you simply copy and paste code from main bot script to cogs...
> Add missing `self` keywords in command function arguments in reddit cog

- main.py
Even Pycord is teaching me vocabulary now 💀
> Replace all `hidden=True` arguments with `ephemeral=True` in `respond()` functions

- main.py
In simple words, it's basically replacing the entire threading system with an asyncio delay system. `asyncio.sleep()`
> Fix issue where Presents daemon thread hangs the main bot client and commands

- main.py
This took so much trial and error to figure out...
> Add `/event leaderboard` command for New Years special event

- main.py
> Prevent database key initializer from resetting all guild warnings when making key for new user

- automod.py
> Add missing `self` keyword args in automod cog commands

- levelling.py
- main.py
> Move levelling system commands from main bot script to cog

- economy.py
- main.py
This has literally become the cog revolution
> Move some big economy system commands from main bot script to cog

- economy.py
Helpful when using a multi-cog setup, like in isobot.
> Add database recaching in economy commands in cog

- main.py
Just another quality-of-life improvement...
> Hide inventory items in inventory embed when command author does not own them

- economy.py
- main.py
* Fixed file stream errors with currency db in main bot script
* Removed recaching system
* Fixed issues related to `max` keyword in withdraw command
* Moved another economy system command from main bot script to economy cog
* Add new command for viewing special event presents count: `/event stats`
* Added built-in library functions for fetching networth, wallet and bank balances from users in economy system
> Fix critical bugs and improve/optimize economy system

- main.py
Sometimes, these kinds of slight changes are the most annoying.
> Switch from discord.py based `avatar_url` user context property to Pycord based `avatar` user context property

- main.py
> Reject new present drops after hitting New Years timestamp

- cogs/economy.py
- cogs/minigames.py
- cogs/moderation.py
So basically I realised that this new cooldown system is irrelevant, and I was probably using the wrong cooldown handler.
(Reverts PyBotDevs/isobot#235)
> Revert "Implement new cooldown system for slash commands with cooldowns"

- main.py
> Patch cooldown handler to support Pycord slash commands

- cogs/utils.py
PyLint is very, **very** misleading.
> Fix module import errors in utils cog on bot initialization

- main.py
I keep forgetting to do these kind of things ☠️ 
Like, literally, **every single time**
> Add utils cog loading to bot initialization sequence

- main.py
I don't even know how I messed this one up, and didn't even realise for so long 🗿
> Fix interaction response context errors in error handler

- main.py
> Remove all redundant functions from main file

- main.py
This helps with memory management and also reduces bloat by a little bit.
> Remove unused database initialization in main file

- cogs/economy.py
- framework/isobot/db/userdata.py
- main.py
> Migrate UserData system completely to a framework module

- cogs/automod.py
- framework/isobot/db/automod.py
- main.py
Even more framework modules!!!
> Migrate all automod db functions to a framework module

- cogs/utils.py
Due to repeated and continuous issues with OpenAI integration in isobot, the isobot AI commands will be temporarily disabled, until further notice.
Thank you for showing your interest in the isobot AI commands!
> Disable all AI-related commands

- config/shop.json
This update includes the addition of items from the **♟ Chess Collection Set**, as well as the `computer` item to pair with the `/hack` command. Best yet, these items are currently now available to buy, sell, and trade with in the shop!
> Add new items to the shop database

- cogs/levelling.py
This is not a joke. I actually finally fixed it.
> Fix issue in `/leaderboard_levels` where bot was unable to fetch user context data from API

- main.py
> Fix an issue where isobot would not give an AFK response when a mentioned user is AFK

- cogs/utils.py
Hopefully to add less confusion for people...
> Add `BOT` flag to bot users in `/whoami`

- main.py
Let's be real here, who *really* wants a swear-filter in an NSFW channel?
> Automatically disregard swear-filter and message checks for all NSFW channels
